package edu.maimonides.multimedia.shapes4learn.model;

/**
 * This empty class represents a Token generated by the lexical analyzer. It
 * will be implemented by the students according to the language and interpreter
 * requirements.
 * 
 * @author Matias Giorgio
 * 
 */
public class Token {

	String tipoToken;
	String lexema;
	boolean validez;

	public String getTipoToken() {
		return tipoToken;
	}

	public void setTipoToken(String tipoToken) {
		this.tipoToken = tipoToken;
	}

	public String getLexema() {
		return lexema;
	}

	public void setLexema(String lexema) {
		this.lexema = lexema;
	}

	public Boolean getValidez() {
		return validez;
	}

	public void setValidez(Boolean validez) {
		this.validez = validez;
	}
}
